Feature/models
ag-students/rails-service pull request #8
Opened 2021-07-05 23:24 UTC by paveldolgov4

resolve #3

2021-07-06 07:15 UTC, Kirchberg commented
PR делаем в develop, а не в main :)

2021-07-06 16:12 UTC, mikeGEINE commented
@paveldolgov4 @HusyaKl а в чем прикол моделей profile и user? Они не одно и то же описывают?

2021-07-06 16:37 UTC, paveldolgov4 commented
@mikeGEINE, вроде бы @argent-smith предложил так делать. В одной модели логин и пароль, а в другой информация по пациенту уже

2021-07-06 16:39 UTC, mikeGEINE commented
> @mikeGEINE, вроде бы @argent-smith предложил так делать. В одной модели логин и пароль, а в другой информация по пациенту уже

А, sorry, только что увидел ту задачу, проморгал)
Вопросов больше не имею 😉

2021-07-09 09:30 UTC, argent-smith requested changes
Пожелания высказал устно

2021-07-12 08:39 UTC, argent-smith requested changes
прогнать `bundle exec rubocop -A` и доработь по оставшимся репортам линтеров

2021-07-12 08:39 UTC, argent-smith commented on app/controllers/confirmations_controller.rb
> +    def after_confirmation_path_for(resource_name, resource)
use `_`

2021-07-14 08:15 UTC, argent-smith approved these changes

2021-07-14 08:15 UTC, argent-smith commented on db/migrate/20210706002719_add_confirmable_to_devise.rb
> + # Note: You can't use change, as User.update_all will fail in the down migration
Объявить модель локально

2021-07-14 08:15 UTC, argent-smith commented on db/migrate/20210709063303_add_columns_to_profiles.rb
> +    add_column :profiles, :adress, :string
`null: false`; + валидации в модели

2021-07-14 08:15 UTC, argent-smith commented on db/migrate/20210709063754_create_roles.rb
> +      t.string :role
-> `:name`

2021-07-14 08:15 UTC, argent-smith commented on db/migrate/20210709064546_create_registrations.rb
> +      t.references :doctor, null: false, foreign_key: {to_table: :users}
`:foreign_key` не используем

2021-07-19 08:20 UTC, Kirchberg approved these changes

2021-07-20 08:15 UTC, argent-smith commented
@HusyaKl напишу в комментах к коду, что сделать

2021-07-20 08:52 UTC, argent-smith requested changes
@HusyaKl я написал, где поправить. Сделаешь — пингани, посмотрим CI ещё раз

2021-07-20 08:52 UTC, argent-smith commented on app/models/user.rb
> +  validates :index_users_on_reset_password_token, uniqueness: true, presence: true
```ruby
validates :reset_password_token, uniqueness: true, presence: true
```

2021-07-20 08:52 UTC, argent-smith commented on app/models/user.rb
> +  validates :index_users_on_confirmation_token, uniqueness: true, presence: true
```ruby
validates :confirmation_token, uniqueness: true, presence: true
```

2021-07-20 08:52 UTC, argent-smith commented on app/models/appointment.rb
> +  belongs_to :patient, class_name: 'User', foreign_key: :patient_id
```ruby
belongs_to :patient, class_name: 'User', inverse_of: :appointments
```

2021-07-20 08:52 UTC, argent-smith commented on app/models/appointment.rb
> +  belongs_to :doctor, class_name: 'User', foreign_key: :doctor_id
```ruby
belongs_to :doctor, class_name: 'User', inverse_of: :appointments
```

2021-07-20 08:52 UTC, argent-smith commented on db/migrate/20210705215517_add_devise_to_users.rb
> +      t.string :email,              null: false, default: ""
default убираем

2021-07-20 08:52 UTC, argent-smith commented on app/models/user.rb
> +end
```ruby
validates :email, presence: true, uniqueness: true
```

2021-07-20 08:52 UTC, argent-smith commented on app/models/profile.rb
> +  validates :gender, :birthday, :weight, :adress, presence: true
в конце этой строки лишний пробел

2021-07-22 08:42 UTC, merged